### ISSUE TITLE
feat: github template configuration

### ISSUE THREAD

**Issue by poiu694** [mash-up-kr/VitaminC_Web#1]
## Description

이슈, PR 템플릿을 설정하여 깃허브 세팅을 진행합니다. [CODEOWENRS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) 파일을 통해 코드의 소유권과 자동 리뷰어를 만듭니다.

## Tasks

- [ ] 이슈 템플릿 작성
- [ ] PR 템플릿 작성
- [ ] CODEOWNERS 파일 작성
